### ISSUE TITLE
Don't update the dropbox?

### ISSUE THREAD

**Issue by bw4sz** [weecology/EvergladesTools#105]
I've been cleaning up the directories, but if we run rsync, we will just replace all the files i've removed. We need to find a way to rsync only new files? Its very difficult to clean up these data on dropbox without command line tools.

**Comment by bw4sz** [comment]
I have turned off the crontab for the moment.

**Comment by ethanwhite** [comment]
This was a good idea since when we resynced recently it did trampled some of the cleaning that both you and I have done. Sadly this probably includes a bunch of projection and band fixing that I spent a bunch of time on last year (though maybe I actually uploaded those changes to Dropbox?).

Not actively syncing the Dropbox feels hard and suboptimal (what if we legitimately update a file), so I'm wondering if the best route isn't to ensure that the Dropbox version is the version of record (or always the same as the version of record) so that we can sync without worrying about it.

Related: #111 

Thoughts?

**Comment by ethanwhite** [comment]
@henrykironde - curious on your thoughts about this

**Comment by ethanwhite** [comment]
The decision we made on this that the Dropbox copy of files is considered the primary version, so any changes that need to be made should either be made to the Dropbox copy and then synced to the the HPC or simultaneously changed in both places.
